// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgReviseWithdrawal } from "./types/bridge/tx";
import { MsgRequestWithdraw } from "./types/bridge/tx";
import { MsgSignWithdrawal } from "./types/bridge/tx";
import { MsgAttestTransfer } from "./types/bridge/tx";


export { MsgReviseWithdrawal, MsgRequestWithdraw, MsgSignWithdrawal, MsgAttestTransfer };

type sendMsgReviseWithdrawalParams = {
  value: MsgReviseWithdrawal,
  fee?: StdFee,
  memo?: string
};

type sendMsgRequestWithdrawParams = {
  value: MsgRequestWithdraw,
  fee?: StdFee,
  memo?: string
};

type sendMsgSignWithdrawalParams = {
  value: MsgSignWithdrawal,
  fee?: StdFee,
  memo?: string
};

type sendMsgAttestTransferParams = {
  value: MsgAttestTransfer,
  fee?: StdFee,
  memo?: string
};


type msgReviseWithdrawalParams = {
  value: MsgReviseWithdrawal,
};

type msgRequestWithdrawParams = {
  value: MsgRequestWithdraw,
};

type msgSignWithdrawalParams = {
  value: MsgSignWithdrawal,
};

type msgAttestTransferParams = {
  value: MsgAttestTransfer,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgReviseWithdrawal({ value, fee, memo }: sendMsgReviseWithdrawalParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgReviseWithdrawal: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgReviseWithdrawal({ value: MsgReviseWithdrawal.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgReviseWithdrawal: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRequestWithdraw({ value, fee, memo }: sendMsgRequestWithdrawParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRequestWithdraw: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRequestWithdraw({ value: MsgRequestWithdraw.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRequestWithdraw: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSignWithdrawal({ value, fee, memo }: sendMsgSignWithdrawalParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSignWithdrawal: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSignWithdrawal({ value: MsgSignWithdrawal.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSignWithdrawal: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAttestTransfer({ value, fee, memo }: sendMsgAttestTransferParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAttestTransfer: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAttestTransfer({ value: MsgAttestTransfer.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAttestTransfer: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgReviseWithdrawal({ value }: msgReviseWithdrawalParams): EncodeObject {
			try {
				return { typeUrl: "/dflow.bridge.MsgReviseWithdrawal", value: MsgReviseWithdrawal.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgReviseWithdrawal: Could not create message: ' + e.message)
			}
		},
		
		msgRequestWithdraw({ value }: msgRequestWithdrawParams): EncodeObject {
			try {
				return { typeUrl: "/dflow.bridge.MsgRequestWithdraw", value: MsgRequestWithdraw.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRequestWithdraw: Could not create message: ' + e.message)
			}
		},
		
		msgSignWithdrawal({ value }: msgSignWithdrawalParams): EncodeObject {
			try {
				return { typeUrl: "/dflow.bridge.MsgSignWithdrawal", value: MsgSignWithdrawal.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSignWithdrawal: Could not create message: ' + e.message)
			}
		},
		
		msgAttestTransfer({ value }: msgAttestTransferParams): EncodeObject {
			try {
				return { typeUrl: "/dflow.bridge.MsgAttestTransfer", value: MsgAttestTransfer.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAttestTransfer: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseUrl: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]>;

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });
		this.tx = txClient({ signer: client.signer, addr: client.env.rpcURL, prefix: client.env.prefix ?? "cosmos" });
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			DflowBridge: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;