// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgInitSsaccount } from "./types/ssaccount/tx";
import { MsgSetSigningKeys } from "./types/ssaccount/tx";
import { MsgCreateNetworkAccount } from "./types/ssaccount/tx";


export { MsgInitSsaccount, MsgSetSigningKeys, MsgCreateNetworkAccount };

type sendMsgInitSsaccountParams = {
  value: MsgInitSsaccount,
  fee?: StdFee,
  memo?: string
};

type sendMsgSetSigningKeysParams = {
  value: MsgSetSigningKeys,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateNetworkAccountParams = {
  value: MsgCreateNetworkAccount,
  fee?: StdFee,
  memo?: string
};


type msgInitSsaccountParams = {
  value: MsgInitSsaccount,
};

type msgSetSigningKeysParams = {
  value: MsgSetSigningKeys,
};

type msgCreateNetworkAccountParams = {
  value: MsgCreateNetworkAccount,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgInitSsaccount({ value, fee, memo }: sendMsgInitSsaccountParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgInitSsaccount: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgInitSsaccount({ value: MsgInitSsaccount.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgInitSsaccount: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSetSigningKeys({ value, fee, memo }: sendMsgSetSigningKeysParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSetSigningKeys: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSetSigningKeys({ value: MsgSetSigningKeys.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSetSigningKeys: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateNetworkAccount({ value, fee, memo }: sendMsgCreateNetworkAccountParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateNetworkAccount: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateNetworkAccount({ value: MsgCreateNetworkAccount.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateNetworkAccount: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgInitSsaccount({ value }: msgInitSsaccountParams): EncodeObject {
			try {
				return { typeUrl: "/dflow.ssaccount.MsgInitSsaccount", value: MsgInitSsaccount.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgInitSsaccount: Could not create message: ' + e.message)
			}
		},
		
		msgSetSigningKeys({ value }: msgSetSigningKeysParams): EncodeObject {
			try {
				return { typeUrl: "/dflow.ssaccount.MsgSetSigningKeys", value: MsgSetSigningKeys.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSetSigningKeys: Could not create message: ' + e.message)
			}
		},
		
		msgCreateNetworkAccount({ value }: msgCreateNetworkAccountParams): EncodeObject {
			try {
				return { typeUrl: "/dflow.ssaccount.MsgCreateNetworkAccount", value: MsgCreateNetworkAccount.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateNetworkAccount: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseUrl: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]>;

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });
		this.tx = txClient({ signer: client.signer, addr: client.env.rpcURL, prefix: client.env.prefix ?? "cosmos" });
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			DflowSsaccount: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;